### ISSUE TITLE
Wrong variable names

### ISSUE THREAD

**Issue by anakin001** [Faisalkc4u/uae_pass#2]
In uae_pass.dart:
   line 11: remove '://'
   line40: getAuthToken -> getAccessToken
In uae_pass_method_channel.dart:
   line 40: getAuthToken -> getAccessToken
   line 41:auth_token -> access_token
In uae_pass_platform_interface.dart:
   line 35 & 36: getAccessToken

**Comment by Faisalkc4u** [comment]
@anakin001 Thanks for the comments

**Comment by anakin001** [comment]
In uae_pass_method_channel.dart:
line 49:auth_token -> access_token
this has not been resolved

**Comment by faisalkcmvp** [comment]
I created another method for that

https://github.com/Faisalkc4u/uae_pass/blob/998fe6b76edd7e7ea13d0861834f91f05a65cf45/lib/uae_pass_method_channel.dart#L50

**Comment by faisalkcmvp** [comment]
Once you receive the access auth token, better to use this method to convert to auth code to the access token. 
Both android and iOS work differently.
 
```
curl --location --request POST 'https://stg-id.uaepass.ae/idshub/token?grant_type=authorization_code&redirect_uri=https://stg-selfcare.uaepass.ae&code=bfe96299-83f4-3ee9-80e4-56c24f5265d3' \
--header 'Content-Type: multipart/form-data' \
--header 'Authorization: Basic c2FuZGJveF9zdGFnZTpzYW5kYm94X3N0YWdl'
```

**Comment by anakin001** [comment]
https://github.com/Faisalkc4u/uae_pass/blob/6ece944f25612092ecc5db00c5bf9bd8c2e438d3/android/src/main/kotlin/com/mvpapps/uae_pass_flutter/UaePassFlutterPlugin.kt#L157

auth_token wasnt implemented

**Comment by Faisalkc4u** [comment]
Both android and ios behave differently

Android to get auth token we need call the sign in again
ios It converts the auth code token token directly 

For a best approach do it on the flutter by using dio/http package or server side.

Once received the auto code you can convert it by hitting the POST method [Refer here](https://github.com/Faisalkc4u/uae_pass#access-token).

**Comment by anakin001** [comment]
![image](https://github.com/Faisalkc4u/uae_pass/assets/62232054/8520a609-5d1f-4c9f-84da-72b7cfab8caa)

This is my code, Ive tested in android, I managed to get the user info.
Not sure if it works on IOS

**Comment by faisalkcmvp** [comment]
Don't use the _usePassPlugin.getAccessToken()

instead use

```
  final FormData formData = FormData.fromMap({
      "grant_type": "authorization_code",
      "redirect_uri": "https://stg-selfcare.uaepass.ae",
      "code": "bfe96299-83f4-3ee9-80e4-56c24f5265d3"
    });

    String username = 'client_id';
    String password = 'client_secret';
    String basicAuth =
        'Basic ${base64.encode(utf8.encode('$username:$password'))}';
    Dio().post("https://stg-id.uaepass.ae/idshub/token",
        data: formData,
        options: Options(headers: {"Authorization": basicAuth}));
```

**Comment by anakin001** [comment]
> Don't use the _usePassPlugin.getAccessToken()
> 
> instead use
> 
> ```
>   final FormData formData = FormData.fromMap({
>       "grant_type": "authorization_code",
>       "redirect_uri": "https://stg-selfcare.uaepass.ae",
>       "code": "bfe96299-83f4-3ee9-80e4-56c24f5265d3"
>     });
> 
>     String username = 'client_id';
>     String password = 'client_secret';
>     String basicAuth =
>         'Basic ${base64.encode(utf8.encode('$username:$password'))}';
>     Dio().post("https://stg-id.uaepass.ae/idshub/token",
>         data: formData,
>         options: Options(headers: {"Authorization": basicAuth}));
> ```

thanks @faisalkcmvp

**Comment by anakin001** [comment]
![image](https://github.com/Faisalkc4u/uae_pass/assets/62232054/fda10a75-ff3b-40cb-88e0-ff44ac5a0d56)
Is it normal that I dont get a refresh token in response? Or it's not available in staging?

**Comment by faisalkcmvp** [comment]
Am not sure about that,
At this stage, you need an access_token to get the user info.

Note: 
- There are different [scopes](https://github.com/Faisalkc4u/uae_pass#scopes-are-as-follows) are available, maybe because of that  
- If you are using ```client: sandbox_stage secret: sandbox_stage``` from the [official doc](https://docs.uaepass.ae/getting-started/testing-credentials) then, After approvels you will get another one.
